uid = rsync                  # 运行进程的系统用户
gid = rsync                  # 运行进程的系统用户组
port = 873                   # 监听端口
fake super = yes             # 允许非 root 用户保存文件的完整属性
use chroot = no              # 安全相关，通常关掉
max connections = 200        # 最大连接数
timeout = 600                # 超时时间
ignore errors                # 忽略无关错误
read only = false            # 允许客户端上传（非只读）
list = false                 # 拒绝客户端查看服务端模块列表（安全）
auth users = rsync_backup    # 创建用于 rsync 协议认证的租户
secrets file = /etc/rsync.passwd # 租户的密码文件路径
log file = /var/log/rsyncd.log   # 日志文件

[backup]                     # 模块名称（客户端租户推送时填写的名字）
comment = welcome to backup!
path = /backup               # 真实的物理存储路径